name: build
on:
  push:
    tags-ignore:
      - '*'
  pull_request:
  workflow_dispatch:
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,macos-latest]
        # without-x:
        # - false: automatically configure X11
        # - true: disable building with X11 (use --without-x option)
        without-x: [false,true]
        # used for macos runner
        homebrew-prefix: [ '/usr/local' ]
        include:
          - os: macos-latest
            without-x: false
            homebrew-prefix: '/Users/runner/homebrew'
    steps:
      - uses: actions/checkout@v2
      - name: Pre-reqs (apt)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get -y update && sudo apt-get install build-essential \
            libpng-dev zlib1g-dev libx11-dev libxaw7-dev libxt-dev x11proto-core-dev libgif-dev
      - name: Prepare Homebrew
        if: runner.os == 'macOS'
        run: |
          echo "Using Homebrew prefix: ${{ matrix.homebrew-prefix }}"
          if [ "${{ matrix.homebrew-prefix }}" = "/usr/local" ]; then
            echo "LIBRARY_PATH=$(brew --prefix)/lib${LIBRARY_PATH:+:${LIBRARY_PATH}}" >> $GITHUB_ENV
          else
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
            git clone https://github.com/Homebrew/brew.git "${{ matrix.homebrew-prefix }}"
            echo "${{ matrix.homebrew-prefix }}/bin" >> $GITHUB_PATH
          fi
      - name: Pre-reqs (homebrew)
        if: runner.os == 'macOS'
        run: |
          brew reinstall gfortran
          brew install automake \
            libpng \
            libxt
      - name: Bootstrap
        run: |
          sh ./bootstrap
      - name: Configure
        run:
          sh ./configure
            ${{ fromJSON('[ "", "--without-x" ]')[ matrix.without-x ] }}
      - name: Make
        run: |
          make
      - name: Show pkg-config files
        run: |
          head -n100 *.pc
